### ISSUE TITLE
Storable Attribute Table name

### ISSUE THREAD

**Issue by webmasterbbc** [CoreHelpers/AzureStorageTable#12]
1) I tried to use this for my Entity Model.. but got an error that gave me an error about getItem not found in Dictionary.. for a fully qualified model name (namespace with model name) when I called  

await storageContext.CreateTableAsync<MyTableName>();

**[Storable("MyTableName")]**

2) After a while of troubleshooting.. I saw your example that explicity specifies Tablename.. so I tried it and it worked.. just wanted to let you know.

**[Storable(Tablename: "MyTableName")]**

Thank you.  

It could be something else on my end but I wanted to pass along just in case..

**Comment by dei79** [comment]
Hello @webmasterbbc, thanks a lot for this information. I will look into the code to figure out why the second version works and the first one not.

**Comment by DavidVollmers** [comment]
This behaviour is not reproducable anymore. Using the constructor parameter of the attribute works in the current version.

Feel free to comment on this issue if it still persists for you.
